"""v0 of database

Revision ID: 9b93b96960a7
Revises: 
Create Date: 2018-11-13 17:32:48.916979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b93b96960a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=256), nullable=True),
    sa.Column('state', sa.String(length=64), nullable=True),
    sa.Column('zip_code', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city', 'state', 'zip_code', name='uniqueLocation')
    )
    op.create_index(op.f('ix_location_city'), 'location', ['city'], unique=False)
    op.create_index(op.f('ix_location_state'), 'location', ['state'], unique=False)
    op.create_index(op.f('ix_location_zip_code'), 'location', ['zip_code'], unique=False)
    op.create_table('artist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('spotify_url', sa.String(length=256), nullable=True),
    sa.Column('youtube_url', sa.String(length=256), nullable=True),
    sa.Column('facebook_url', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_artist_description'), 'artist', ['description'], unique=False)
    op.create_index(op.f('ix_artist_name'), 'artist', ['name'], unique=True)
    op.create_table('porchfest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_id', 'start_time', name='uniquePorchfest')
    )
    op.create_table('porch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('address', sa.String(length=256), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('porchfest_id', sa.Integer(), nullable=True),
    sa.Column('time_available_start', sa.DateTime(), nullable=True),
    sa.Column('time_available_end', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['porchfest_id'], ['porchfest.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address', 'location_id', 'porchfest_id', name='uniquePorch')
    )
    op.create_table('artist_to_porch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('porch_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
    sa.ForeignKeyConstraint(['porch_id'], ['porch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artist_to_porch')
    op.drop_table('porch')
    op.drop_table('porchfest')
    op.drop_index(op.f('ix_artist_name'), table_name='artist')
    op.drop_index(op.f('ix_artist_description'), table_name='artist')
    op.drop_table('artist')
    op.drop_index(op.f('ix_location_zip_code'), table_name='location')
    op.drop_index(op.f('ix_location_state'), table_name='location')
    op.drop_index(op.f('ix_location_city'), table_name='location')
    op.drop_table('location')
    # ### end Alembic commands ###
